npcs:
  - §9Hotbar Manager::bffa hotbarmanager
  - §3Kits!::bffa kits
  - §4Leave::bw leave

# the seconds of combat log.
combatlog: 10
void-height: 20
# the seconds till a block placed disappears
block-disappearing: 8

# the seconds till a broken block re-appears
block-appearing: 9

# the count of custom messages. Increase it if you are adding more custom kills messages
deathmessages: 3
messages:
  death-by-player-1: "§3%victim% §7got killed by §b%attacker%"
  death-by-player-2: "§3%victim% §7got smoked by §b%attacker%"
  death-by-player-3: "§3%victim% §7got railed by §b%attacker%"
  death-by-void: "§3%victim% §7fell in the void."
  death-unknown: "§c%victim% §7died (we don't know how)."
  chat-formatting: "%luckperms_prefix%%player% %luckperms_suffix%§7 §9[§b§lBuild§3§lFFA§9]: §f%message%"
  leave-message: "§7%player% §eleft BuildFFA"
  join-message: "§7%player% §ejoined BuildFFA"

scoreboard:
  scoreboard-name: "§b§lBuild§3§lFFA"
  top-kills: "§7Top Killstreak: §b%player%"
  kills: "§7Kills: §b%kills%"
  deaths: "§7Deaths: §3%deaths%"
  killstreak: "§7KillStreak: §b%killstreak%"
  deathstreak: "§7DeathStreak: §3%deathstreak%"
  ip: "§TOSET.it"

killsrewards:
  # Example
  # choose the kill by changing the number after kills MAX IS 50, after 50 there's 50+ that gets flagged everytime you kill someone at 50 killstreak
  # Kills10:
  #        ==: org.bukkit.inventory.ItemStack
  #        type: WOOD_SWORD
  '1':
    item1:
      ==: org.bukkit.inventory.ItemStack
      type: GOLDEN_APPLE
  '2':
    item1:
      ==: org.bukkit.inventory.ItemStack
      type: GOLDEN_APPLE
    item2:
      ==: org.bukkit.inventory.ItemStack
      type: ENDER_PEARL
  '3':
    item1:
      ==: org.bukkit.inventory.ItemStack
      type: GOLDEN_APPLE
      amount: 2
    item2:
      ==: org.bukkit.inventory.ItemStack
      type: ENDER_PEARL
      amount: 1
  '4':
    item1:
      ==: org.bukkit.inventory.ItemStack
      type: GOLDEN_APPLE
      amount: 2
    item2:
      ==: org.bukkit.inventory.ItemStack
      type: ENDER_PEARL
      amount: 1
    item3:
      potion: jump
  '5':
    item1:
      ==: org.bukkit.inventory.ItemStack
      type: GOLDEN_APPLE
      amount: 2
    item2:
      ==: org.bukkit.inventory.ItemStack
      type: ENDER_PEARL
      amount: 1
    item3:
      ==: org.bukkit.inventory.ItemStack
      type: FIREBALL
      amount: 1
    item4:
      potion: jump
  '6':
    item1:
      ==: org.bukkit.inventory.ItemStack
      type: GOLDEN_APPLE
      amount: 2
    item2:
      ==: org.bukkit.inventory.ItemStack
      type: ENDER_PEARL
      amount: 1
    item3:
      ==: org.bukkit.inventory.ItemStack
      type: FIREBALL
      amount: 2
    item4:
      potion: jump
    item5:
      potion: invisibility
  others:
    item1:
      ==: org.bukkit.inventory.ItemStack
      type: GOLDEN_APPLE
      amount: 3
    item2:
      ==: org.bukkit.inventory.ItemStack
      type: ENDER_PEARL
      amount: 1
    item3:
      ==: org.bukkit.inventory.ItemStack
      type: FIREBALL
      amount: 1
    item4:
      potion: jump
    item5:
      potion: invisibility

spawnloc:
  ==: org.bukkit.Location
  world: buildffa
  x: 6
  y: 143.0
  z: 0
  pitch: 0.6
  yaw: 90.5

maxbuildy: 89
kitslist:
  # list of the kits, make sure to add them here.
  - default
kitperms:
  # add kits perms here use NONE if you want it for everyone
  default: NONE
kits:
  # add new kits voices here, make sure you added the same kit in kitperms and kitslist
  default:
    armor:
      # armors. to add enchants you can copy this:
      #
      # meta:
      #  ==: ItemMeta
      #  meta-type: UNSPECIFIC
      #  enchants:
      #    DAMAGE_ALL: 1
      cap:
        ==: org.bukkit.inventory.ItemStack
        type: LEATHER_HELMET
        meta:
          ==: ItemMeta
          meta-type: LEATHER_ARMOR
          color:
            ==: Color
            RED: 255
            BLUE: 85
            GREEN: 85
      chestplate:
        ==: org.bukkit.inventory.ItemStack
        type: LEATHER_CHESTPLATE
        meta:
          ==: ItemMeta
          meta-type: LEATHER_ARMOR
          color:
            ==: Color
            RED: 255
            BLUE: 85
            GREEN: 85
      leggins:
        ==: org.bukkit.inventory.ItemStack
        type: DIAMOND_LEGGINGS
      boots:
        ==: org.bukkit.inventory.ItemStack
        type: DIAMOND_BOOTS
    items:
      # add slots
      slot0:
        ==: org.bukkit.inventory.ItemStack
        type: STONE_SWORD
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            DAMAGE_ALL: 1
      slot1:
        ==: org.bukkit.inventory.ItemStack
        type: WOOL
        amount: 64
      slot2:
        ==: org.bukkit.inventory.ItemStack
        type: SHEARS
      slot3:
        ==: org.bukkit.inventory.ItemStack
        type: IRON_PICKAXE
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            DIG_SPEED: 1